# docker-compose.yml

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always